### ISSUE TITLE
部署成功后，主页 `404`

### ISSUE THREAD

**Issue by Cactusinhand** [ChrAlpha/ginb#1]
`archives`, `tags` 页的请求正常，主页 `/` 请求错误：
![image](https://github.com/user-attachments/assets/a521278b-8b1d-417c-a727-81db615cb7b0)

![image](https://github.com/user-attachments/assets/1dcd4e16-ccf3-48f9-b0d4-ce2e3c2a895a)

另外，关联的 issue 的仓库不是必须公开的吧。奇怪的是我创建了 issue, 还打了标签，vercel 上却没有任何数据。

**Comment by ChrAlpha** [comment]
本地测试的情况呢？信息不够不便定位问题。

> 另外，关联的 issue 的仓库不是必须公开的吧。

可以不公开，[Demo](https://ginb.ichr.me) 的仓库就是 private 的
